// Copyright 2018 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generator

const fileTemplate = `{{ $tick := "` + "`" + `" }}// Code generated by tdt2go
// DO NOT EDIT! ANY CHANGES MAY BE OVERWRITTEN.

package {{.Package}}
{{- if gt (len .Imports) 0}}

import (
{{- range .Imports }}
	"{{ . }}"
{{- end }}
){{ end }}
{{- range .DataTypes}}

// {{.Name}} is the generated representation of {{.FQDTN}} data type{{ if .Description }}
//
// {{ asComment .Description }}{{end}}
type {{.Name}} {{ if and (ne .DerivedFrom "") (eq (len .Fields) 0) }}{{.DerivedFrom}}{{ else }}struct {
{{- if ne .DerivedFrom ""}}
	{{.DerivedFrom}}
{{- end}}
	{{- range .Fields}}{{ if .Description }}
	// {{ asComment .Description }}{{end}}
	{{.Name}} {{.Type}} {{- if ne .OriginalName ""}} {{ $tick }}mapstructure:"{{.OriginalName}}" json:"{{.OriginalName}},omitempty"{{ $tick }}{{end}}{{end}}
}
{{end}}{{end -}}
`
