package generator

const fileTemplate = `{{ $tick := "` + "`" + `" }}// Code generated by tdt2go
// DO NOT EDIT! ANY CHANGES MAY BE OVERWRITTEN.

package {{.Package}}
{{- if gt (len .Imports) 0}}

import (
{{- range .Imports }}
	"{{ . }}"
{{- end }}
){{ end }}
{{- range .DataTypes}}

// {{.Name}} is the generated representation of {{.FQDTN}} data type
type {{.Name}} struct {
{{- if ne .DerivedFrom ""}}
	{{.DerivedFrom}}
{{- end}}
	{{- range .Fields}}
	{{.Name}} {{.Type}} {{- if ne .OriginalName ""}} {{ $tick }}mapstructure:"{{.OriginalName}}" json:"{{.OriginalName}},omitempty"{{ $tick }}{{end}}{{end}}
}
{{end -}}
`
